/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: [
      'www.themealdb.com',
      'uploaddeimagens.com.br',
      'images.unsplash.com',
      'softpig.com.br',
      'www.anamariareceitas.com.br',
      'img.cybercook.com.br',
      'www.feitodeiridium.com.br',
      'chocolatecoveredkatie.com',
      'www.hipertrofia.org',
      'thumbs.dreamstime.com',
      'img.freepik.com',
      'www.mundoboaforma.com.br',
      'www.plantte.com',
      'tribunademinas.com.br',
      'static.itdg.com.br',
      'receitinhas.com.br',
      'i.panelinha.com.br',
      'www.receiteria.com.br',
      'www.pingodoce.pt',
      'naminhapanela.com',
      'boomi.b-cdn.net',
      'www.famintas.com.br',
      'png.pngtree.com',
      'www.fula.pt',
      'vitat.com.br',
      'assets.tmecosys.com',
      'www.hojetemfrango.com.br',
      'www.receiteria.com.br',
      'guiadacozinha.com.br',
      'marolacomcarambola.com.br',
      'd1uz88p17r663j.cloudfront.net',
      'dietamais.com',
      'f.i.uol.com.br',
      'swiftbr.vteximg.com.br',
      'assets.unileversolutions.com',
      'octoshop.sfo2.digitaloceanspaces.com',
      's2.glbimg.com',
      'www.saboresajinomoto.com.br',
    ],
  },
};

module.exports = nextConfig;
